import asyncio
import hashlib
import json
from http import HTTPStatus
from pathlib import Path
from typing import Optional, Set

import typer
from fastapi import FastAPI, HTTPException, Request, WebSocket, WebSocketDisconnect
from fastapi.responses import FileResponse, HTMLResponse
from fastapi.staticfiles import StaticFiles
import uvicorn

from franken_stream.async_scraper import AsyncContentScraper
from franken_stream.cache import FTSCache
from franken_stream.player import PremiumPlayer
from franken_stream.preloader import PredictiveLoader
from franken_stream.providers import ProviderManager
from franken_stream.watchlist import Watchlist
from franken_stream.tmdb_embed import (
    tmdb_configured, tmdb_search, tmdb_trending, tmdb_now_playing,
    tmdb_upcoming, tmdb_genres, tmdb_discover_by_genre,
    is_tmdb_url, resolve_tmdb_embed_all,
)
from franken_stream.iptv_live import list_countries, list_channels
from franken_stream.audio_sources import (
    itunes_search, itunes_album_tracks, podcast_episodes, soundcloud_embed,
    youtube_configured, youtube_search,
)
from franken_stream.musify import musify_search, musify_resolve

app = typer.Typer(help="Web UI server commands")

# Create FastAPI app
web_app = FastAPI(title="Franken-Stream Web UI", version="0.1.0")

# Module-level singletons — shared across all requests
_player = PremiumPlayer()
_watchlist = Watchlist()
_ws_clients: Set[WebSocket] = set()

# Shared scraper + preloader kept alive for the duration of the server process
_shared_pm = ProviderManager()
_shared_scraper: Optional[AsyncContentScraper] = None
_preloader: Optional[PredictiveLoader] = None


def _get_preloader() -> PredictiveLoader:
    global _shared_scraper, _preloader
    if _shared_scraper is None:
        _shared_scraper = AsyncContentScraper(provider_manager=_shared_pm)
        _preloader = PredictiveLoader(_shared_scraper)
    return _preloader

WEB_UI_DIR = Path(__file__).resolve().parent / "web_ui"
INDEX_FILE = WEB_UI_DIR / "index.html"


# Mount static assets generated by Vite build
_ASSETS_DIR = WEB_UI_DIR / "assets"
if _ASSETS_DIR.exists():
    web_app.mount("/assets", StaticFiles(directory=str(_ASSETS_DIR)), name="assets")


@web_app.get("/", response_class=HTMLResponse)
async def root():
    """Serve the main web UI"""
    if not INDEX_FILE.exists():
        raise HTTPException(status_code=404, detail="Web UI not found")
    return FileResponse(INDEX_FILE, media_type="text/html")


@web_app.get("/api/health")
async def get_health():
    """Get provider health status"""
    try:
        pm = ProviderManager()
        health_data = pm.get_health_summary()
        return {"status": "ok", "providers": health_data}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@web_app.get("/api/providers")
async def get_providers():
    """Get available search providers"""
    try:
        pm = ProviderManager()
        search_bases = pm.get_ranked_search_bases()
        return {"status": "ok", "search_bases": search_bases}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


def _enrich(item: dict) -> dict:
    """Pass-through enrichment hook for search results."""
    return item


@web_app.post("/api/v1/search")
async def v1_search(request: Request):
    data = await request.json()
    query = data.get("query", "").strip()
    if not query:
        raise HTTPException(status_code=400, detail="query is required")

    # FTS5 cache check
    fts = FTSCache()
    cached = fts.lookup(query)
    if cached:
        results = [_enrich({"title": t, "url": u}) for t, u in cached]
        asyncio.create_task(_get_preloader().preload(cached[:3]))
        return {"status": "ok", "query": query, "results": results, "cached": True}

    pm = ProviderManager()
    scraper = AsyncContentScraper(provider_manager=pm)
    try:
        bases = pm.get_ranked_search_bases()
        scraper_results, plugin_results = await asyncio.gather(
            scraper.search(query, bases),
            pm.search_plugins(query),
            return_exceptions=True,
        )
        if isinstance(scraper_results, Exception):
            scraper_results = []
        if isinstance(plugin_results, Exception):
            plugin_results = []

        # Merge, dedup by URL (scraper results take priority)
        seen: set = {u for _, u in scraper_results}
        raw = list(scraper_results)
        for title, url in plugin_results:
            if url not in seen:
                seen.add(url)
                raw.append((title, url))

        # Relevance sorting
        def _score(item: Tuple[str, str]) -> float:
            title = item[0].lower()
            q = query.lower()
            if title == q: return 10.0
            
            q_words = [w for w in q.split() if len(w) > 2]
            if not q_words: return 0.0
            
            title_words = title.split()
            
            # Count word matches
            matches = 0
            for qw in q_words:
                if qw in title:
                    matches += 1
                    # Bonus for exact word match
                    if any(tw == qw for tw in title_words):
                        matches += 0.5
            
            # Bonus for phrase match
            if q in title: matches += 2.0
            
            score = float(matches) / len(q_words)
            
            # Penalty for very long titles (often noise)
            if len(title) > 60: score *= 0.8
            
            # Penalty for "random" look (too many non-alphanumeric)
            non_alnum = len([c for c in title if not c.isalnum() and not c.isspace()])
            if non_alnum > 5: score *= 0.7
            
            return score

        raw.sort(key=_score, reverse=True)

        # Filter out generic/low-relevance results
        # Only keep results that match at least one significant query word
        raw = [r for r in raw if _score(r) > 0.5]

        if raw:
            fts.store(query, raw)
        asyncio.create_task(_get_preloader().preload(raw[:3]))
        results = [_enrich({"title": t, "url": u}) for t, u in raw]
        return {"status": "ok", "query": query, "results": results, "cached": False}
    finally:
        await scraper.close()


@web_app.post("/api/search")
async def search(request: Request):
    """Search for movies/shows"""
    try:
        data = await request.json()
        query = data.get("query", "").strip()

        if not query:
            raise HTTPException(status_code=400, detail="Query is required")

        # TMDB-first: real, sanctioned metadata API, not fighting anti-bot.
        # The 9 scraped providers below are ~100% dead (Cloudflare/JWT/JS
        # gates) as of the 2026-07-25 live audit -- kept only as fallback.
        if tmdb_configured():
            tmdb_results = await tmdb_search(query)
            if tmdb_results:
                return {
                    "status": "ok",
                    "query": query,
                    "results": [
                        {"title": r["title"], "url": r["url"], "thumbnail": r["thumbnail"],
                         "year": r.get("year"), "rating": r.get("rating"), "media_type": r.get("media_type")}
                        for r in tmdb_results
                    ],
                    "cached": False,
                    "source": "tmdb",
                }

        # FTS5 cache check
        fts = FTSCache()
        cached = fts.lookup(query)
        if cached:
            return {
                "status": "ok",
                "query": query,
                "results": [{"title": t, "url": u} for t, u in cached],
                "cached": True,
            }

        pm = ProviderManager()
        scraper = AsyncContentScraper(provider_manager=pm)
        try:
            bases = pm.get_ranked_search_bases()
            raw = await scraper.search(query, bases)
            if raw:
                fts.store(query, raw)
            return {
                "status": "ok",
                "query": query,
                "results": [{"title": title, "url": url} for title, url in raw],
                "cached": False,
            }
        finally:
            await scraper.close()
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


def _slim(results: list) -> dict:
    return {"status": "ok", "results": [
        {"title": r["title"], "url": r["url"], "thumbnail": r["thumbnail"],
         "year": r.get("year"), "rating": r.get("rating"), "media_type": r.get("media_type")}
        for r in results
    ]}


@web_app.get("/api/trending")
async def trending(window: str = "week", media_type: str = "all"):
    """No-search-needed grid: trending movies/TV from TMDB."""
    return _slim(await tmdb_trending(window=window, media_type=media_type))


@web_app.get("/api/now-playing")
async def now_playing():
    return _slim(await tmdb_now_playing())


@web_app.get("/api/upcoming")
async def upcoming():
    return _slim(await tmdb_upcoming())


@web_app.get("/api/genres")
async def genres(media_type: str = "movie"):
    return {"status": "ok", "genres": await tmdb_genres(media_type=media_type)}


@web_app.get("/api/discover")
async def discover(genre_id: int, media_type: str = "movie"):
    return _slim(await tmdb_discover_by_genre(genre_id, media_type=media_type))


@web_app.get("/api/live/countries")
async def live_countries():
    """Real Live TV: iptv-org's country list, zero scraping."""
    try:
        return {"status": "ok", "countries": await list_countries()}
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"iptv-org fetch failed: {e}")


@web_app.get("/api/live/channels/{country_code}")
async def live_channels(country_code: str):
    """Real HLS (.m3u8) channel list for a country, from iptv-org's static
    playlists -- these URLs are directly playable (hls.js or native HLS),
    not resolved through /api/embed."""
    try:
        channels = await list_channels(country_code)
        return {"status": "ok", "country": country_code.upper(), "channels": channels}
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"iptv-org fetch failed: {e}")


@web_app.get("/api/audio/search")
async def audio_search(term: str, media: str = "music", entity: Optional[str] = None):
    """Real iTunes Search API results -- albums/songs (media=music) or
    podcasts (media=podcast). Songs carry a legal 30s preview_url;
    podcasts carry a real public feed_url (see /api/audio/podcast/episodes)."""
    if not term.strip():
        raise HTTPException(422, "term is required")
    results = await itunes_search(term.strip(), media=media, entity=entity)
    return {"status": "ok", "results": results}


@web_app.get("/api/audio/album/tracks")
async def audio_album_tracks(collection_id: int):
    """Real per-track preview_urls for an album -- entity=album search
    results never carry one (see itunes_album_tracks' docstring); this is
    the follow-up lookup the frontend calls when a user wants to play an
    album result."""
    tracks = await itunes_album_tracks(collection_id)
    return {"status": "ok", "tracks": tracks}


@web_app.get("/api/audio/podcast/episodes")
async def audio_podcast_episodes(feed_url: str):
    """Real episode list parsed directly from a podcast's public RSS feed
    -- direct, full-length, legal audio URLs, no scraping."""
    episodes = await podcast_episodes(feed_url)
    return {"status": "ok", "episodes": episodes}


@web_app.get("/api/audio/soundcloud/embed")
async def audio_soundcloud_embed(url: str):
    """Real SoundCloud oEmbed lookup for a track/playlist URL the caller
    already has (no key-free full-catalog search exists)."""
    result = await soundcloud_embed(url)
    if not result:
        raise HTTPException(404, "Could not resolve a SoundCloud embed for that URL")
    return {"status": "ok", **result}


@web_app.get("/api/audio/youtube/search")
async def audio_youtube_search(term: str):
    """Official YouTube Data API v3 search -- degrades to empty results
    if YOUTUBE_API_KEY isn't configured, same pattern as TMDB."""
    if not youtube_configured():
        return {"status": "ok", "results": [], "configured": False}
    results = await youtube_search(term)
    return {"status": "ok", "results": results, "configured": True}


@web_app.get("/api/audio/musify/search")
async def audio_musify_search(term: str):
    """Real full-length track search via musify.club. DISCLOSED, NOT
    HIDDEN: unlicensed commercial music mirror, meaningfully higher legal
    risk than the movie-embed providers -- see musify.py's docstring."""
    if not term.strip():
        raise HTTPException(422, "term is required")
    results = await musify_search(term.strip())
    return {"status": "ok", "results": results}


@web_app.get("/api/audio/musify/resolve")
async def audio_musify_resolve(track_url: str):
    """Resolves a musify.club track page to its actual time-limited,
    directly-streamable full-track URL (expires ~1hr, resolve on demand)."""
    stream_url = await musify_resolve(track_url)
    if not stream_url:
        raise HTTPException(404, "Could not resolve a playable stream for that track")
    return {"status": "ok", "stream_url": stream_url}


@web_app.post("/api/embed")
async def get_embed(request: Request):
    """Extract embed URL from a page. Uses the async scraper (not the sync
    ContentScraper) since the crawl4ai + page-agent fallback chain is
    async-only -- see async_scraper.py's fetch_embed_from_page."""
    try:
        data = await request.json()
        page_url = data.get("url")
        base_url = data.get("base_url")

        if not page_url:
            raise HTTPException(status_code=400, detail="URL is required")

        # TMDB search results carry a synthetic `tmdb:{type}:{id}` url --
        # resolve straight to embed-provider URLs, no scraping involved.
        # Returns ALL candidates (not just the first) -- see
        # resolve_tmdb_embed_all's docstring: these embed sites can't be
        # reliably liveness-probed server-side (anti-automation JS runs
        # client-side, after a 200 response), so the frontend needs real
        # alternates to offer "try another source" when one doesn't play.
        if is_tmdb_url(page_url):
            candidates = await resolve_tmdb_embed_all(page_url)
            embed_url = candidates[0]["url"] if candidates else None
            return {"status": "ok", "embed_url": embed_url, "alternates": candidates}

        scraper = AsyncContentScraper(provider_manager=_shared_pm)
        embed_url = await scraper.fetch_embed_from_page(page_url, base_url=base_url)

        return {"status": "ok", "embed_url": embed_url}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ── v1 Provider / Skills ──────────────────────────────────────────────────────

@web_app.get("/api/v1/providers")
async def v1_providers():
    pm = ProviderManager()
    return {
        "status": "ok",
        "search_bases": pm.get_ranked_search_bases(),
        "embed_fallbacks": pm.get_embed_fallbacks(),
        "health": pm.get_health_summary(),
    }


@web_app.get("/api/v1/skills/manifest")
async def v1_skills_manifest():
    return {
        "skill": {
            "id": "franken-stream",
            "name": "Franken-Stream Media Player",
            "version": "2.0.0",
            "description": "Search and play movies/TV shows from multiple providers",
        },
        "endpoints": {
            "base_url": "http://localhost:8000/api/v1",
            "websocket": "ws://localhost:8000/api/ws",
        },
        "actions": {
            "search_media": "POST /api/v1/search",
            "play_media":   "POST /api/v1/player/spin-up",
            "control":      "POST /api/v1/player/control",
            "status":       "GET  /api/v1/player/status",
            "providers":    "GET  /api/v1/providers",
        },
    }


@web_app.get("/api/v1/embed/{media_id}")
async def v1_embed(media_id: str):
    pm = ProviderManager()
    scraper = AsyncContentScraper(provider_manager=pm)
    try:
        embed_url = await scraper.fetch_embed_from_page(media_id)
        return {"status": "ok", "embed_url": embed_url}
    finally:
        await scraper.close()


# ── v1 Playback (direct URL) ──────────────────────────────────────────────────

@web_app.post("/api/v1/play")
async def v1_play(request: Request):
    data = await request.json()
    url = data.get("url", "").strip()
    title = data.get("title", "")
    if not url:
        raise HTTPException(status_code=400, detail="url is required")
    result = await _player.play(url, title=title)
    if result.get("status") == "playing":
        media_id = hashlib.md5(url.encode()).hexdigest()[:12]
        _watchlist.add(media_id, title or url, url)
    await _broadcast({"type": "playback", "event": "started", **result})
    return result


@web_app.post("/api/v1/control")
async def v1_control(request: Request):
    data = await request.json()
    action = data.get("action", "")
    ok = False

    if action == "pause":
        ok = await _player.pause()
    elif action == "resume":
        ok = await _player.resume()
    elif action == "stop":
        await _player.stop()
        ok = True
    elif action == "seek":
        position = data.get("position")
        if position is None:
            raise HTTPException(status_code=400, detail="position required for seek")
        ok = await _player.seek(int(position))
    else:
        raise HTTPException(status_code=400, detail=f"Unknown action: {action}")

    await _broadcast({"type": "playback", "event": action, "ok": ok})
    return {"action": action, "ok": ok}


@web_app.get("/api/v1/status")
async def v1_status():
    return await _player.get_status()


# ── v1 Player (agent one-shot spin-up) ───────────────────────────────────────

@web_app.post("/api/v1/player/spin-up")
async def player_spin_up(request: Request):
    """
    Agent one-shot: search → extract embed → play.
    POST {"query": "Oppenheimer", "quality": "best"}
    """
    data = await request.json()
    query = data.get("query", "").strip()
    if not query:
        raise HTTPException(status_code=400, detail="query is required")

    # 1. Search
    fts = FTSCache()
    cached = fts.lookup(query)
    if cached:
        raw = cached
    else:
        pm = ProviderManager()
        scraper = AsyncContentScraper(provider_manager=pm)
        try:
            bases = pm.get_ranked_search_bases()
            raw = await scraper.search(query, bases)
            if raw:
                fts.store(query, raw)
        finally:
            await scraper.close()

    if not raw:
        raise HTTPException(status_code=404, detail=f"No results found for: {query}")

    title, page_url = raw[0]

    # 2. Extract embed
    pm2 = ProviderManager()
    scraper2 = AsyncContentScraper(provider_manager=pm2)
    try:
        embed_url = await scraper2.fetch_embed_from_page(page_url)
        play_url = embed_url or page_url
    finally:
        await scraper2.close()

    # 3. Spin up player
    result = await _player.play(play_url, title=title)
    if result.get("status") == "error":
        raise HTTPException(status_code=500, detail=result.get("message", "Player error"))

    media_id = hashlib.md5(play_url.encode()).hexdigest()[:12]
    _watchlist.add(media_id, title, play_url)
    await _broadcast({"type": "playback", "event": "spin-up", "title": title})
    return {
        "status": "playing",
        "media": {"title": title, "url": play_url},
        "message": f"Now playing: {title}",
        **result,
    }


@web_app.get("/api/v1/player/status")
async def player_status():
    return await _player.get_status()


@web_app.post("/api/v1/player/control")
async def player_control(request: Request):
    return await v1_control(request)


# ── Watchlist ─────────────────────────────────────────────────────────────────

@web_app.get("/api/v1/watchlist")
async def watchlist_list():
    return {"status": "ok", "items": _watchlist.all()}


@web_app.get("/api/v1/watchlist/in-progress")
async def watchlist_in_progress():
    return {"status": "ok", "items": _watchlist.in_progress()}


@web_app.post("/api/v1/watchlist")
async def watchlist_add(request: Request):
    data = await request.json()
    title = data.get("title", "").strip()
    url = data.get("url", "").strip()
    if not title or not url:
        raise HTTPException(status_code=400, detail="title and url are required")
    media_id = data.get("id") or hashlib.md5(url.encode()).hexdigest()[:12]
    _watchlist.add(
        media_id,
        title,
        url,
        provider=data.get("provider", ""),
        year=data.get("year"),
        media_type=data.get("media_type", "movie"),
        quality=data.get("quality", "unknown"),
    )
    return {"status": "ok", "id": media_id}


@web_app.patch("/api/v1/watchlist/{media_id}")
async def watchlist_update(media_id: str, request: Request):
    data = await request.json()
    progress = data.get("progress_seconds")
    if progress is None:
        raise HTTPException(status_code=400, detail="progress_seconds is required")
    _watchlist.update_progress(media_id, int(progress), data.get("duration_seconds"))
    return {"status": "ok"}


@web_app.delete("/api/v1/watchlist/{media_id}")
async def watchlist_remove(media_id: str):
    _watchlist.remove(media_id)
    return {"status": "ok"}


# ── WebSocket ─────────────────────────────────────────────────────────────────

async def _broadcast(msg: dict) -> None:
    """Push a JSON message to all connected WebSocket clients."""
    dead: Set[WebSocket] = set()
    for ws in list(_ws_clients):
        try:
            await ws.send_json(msg)
        except Exception:
            dead.add(ws)
    _ws_clients.difference_update(dead)


@web_app.websocket("/api/ws")
async def websocket_endpoint(ws: WebSocket):
    await ws.accept()
    _ws_clients.add(ws)
    await ws.send_json({"type": "connected", "message": "Franken-Stream WebSocket ready"})
    try:
        while True:
            data = await ws.receive_json()
            if data.get("action") == "ping":
                await ws.send_json({"type": "pong"})
            elif data.get("action") == "status":
                status = await _player.get_status()
                await ws.send_json({"type": "status", **status})
    except WebSocketDisconnect:
        pass
    finally:
        _ws_clients.discard(ws)


# ── CLI entry point ───────────────────────────────────────────────────────────

@app.callback(invoke_without_command=True)
def serve(
    host: str = typer.Option("127.0.0.1", "--host", "-h", help="Host to bind the web server."),
    port: int = typer.Option(8000, "--port", "-p", help="Port for the web server."),
) -> None:
    """Start the Franken-Stream Web UI server."""
    typer.echo(f"Starting Franken-Stream Web UI at http://{host}:{port}")
    uvicorn.run(web_app, host=host, port=port)
